ALTER TABLE tokens ADD COLUMN IF NOT EXISTS security_data JSONB;

ALTER TABLE tokens ADD COLUMN IF NOT EXISTS solsniffer_score INTEGER;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS solsniffer_checked_at TIMESTAMP;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS security_data JSONB;